MONGODB_HOST: mongodb-{{ env }}.daws86s.sbs # mongodb-dev.daws86s.sbs
REDIS_HOST: redis-{{ env }}.daws86s.sbs
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws86s.sbs
CART_HOST: cart.backend-alb-{{ env }}.daws86s.sbs
USER_HOST: user.backend-alb-{{ env }}.daws86s.sbs
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86s.sbs
MYSQL_HOST: mysql-{{ env }}.daws86s.sbs
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws86s.sbs
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws86s.sbs